#!/bin/sh

export QT_FONT_DPI=96

xrandr --output DP-4 --mode 1920x1080 --output DP-3.1 --mode 1920x1080 --right-of DP-4 --output DP-3.2 --mode 1920x1080 --right-of DP-3.1

setxkbmap cz dvorak
ssh-add
ssh-agent
feh --bg-scale /home/dqd/documents/hubble2.png --bg-scale /home/dqd/documents/hubble1.png
numlockx on
xsetroot -cursor_name left_ptr
xscreensaver -nosplash &
unclutter &
stalonetray &
