#!/bin/bash

# xrdb -merge .Xresources
# xsetroot -solid black
feh --bg-center ~/dokumenty/giger-wallpaper.png &
stalonetray &> /dev/null &
xscreensaver -no-splash &
unclutter &
export OOO_FORCE_DESKTOP="gnome"
 
exec xmonad
